# Generated by Django 3.2.3 on 2021-06-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_form_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='username',
        ),
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.EmailField(max_length=84),
        ),
        migrations.AlterField(
            model_name='form',
            name='item_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
