# Generated by Django 3.2.3 on 2021-06-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210628_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='name',
            new_name='first_name',
        ),
    ]
