# Generated by Django 3.2.3 on 2021-06-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_form_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='item_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='phonenumber',
            new_name='password',
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default=0, max_length=54),
            preserve_default=False,
        ),
    ]
