# Generated by Django 3.2.3 on 2021-07-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210701_1106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='buy',
        ),
    ]
