# Generated by Django 3.2.3 on 2021-07-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_register_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='order',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
