# Generated by Django 3.2.3 on 2021-07-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_buy_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='username',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
