# Generated by Django 3.2.3 on 2021-07-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_buy_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
