# Generated by Django 3.2.3 on 2021-07-17 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_buy_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='order',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='phonenumber',
        ),
    ]
